- project:
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      queue: integrated
      jobs:
        - openstack-tox-pep8
        - cinderlib-tox-py27
        - cinderlib-tox-py36
        - cinderlib-tox-py37

        - cinderlib-lvm-functional
        - cinderlib-ceph-functional
    gate:
      queue: integrated
      jobs:
        - openstack-tox-pep8
        - cinderlib-tox-py27
        - cinderlib-tox-py36
        - cinderlib-tox-py37

        - cinderlib-lvm-functional
        - cinderlib-ceph-functional
    post:
      jobs:
        - publish-openstack-python-branch-tarball

- job:
    name: cinderlib-tox-py27
    parent: openstack-tox-py27
    required-projects:
      - openstack/os-brick
      - openstack/cinder

- job:
    name: cinderlib-tox-py36
    parent: openstack-tox-py36
    required-projects:
      - openstack/os-brick
      - openstack/cinder

- job:
    name: cinderlib-tox-py37
    parent: openstack-tox-py37
    required-projects:
      - openstack/os-brick
      - openstack/cinder

- job:
    name: cinderlib-lvm-functional
    parent: openstack-tox-functional-with-sudo
    required-projects:
      - openstack/os-brick
      - openstack/cinder
    pre-run: playbooks/setup-lvm.yaml
    nodeset: centos-7
    vars:
      tox_environment:
        CL_FTEST_MEMORY_PERSISTENCE: "false"
        # These come from great-great-grandparent tox job
        NOSE_WITH_HTML_OUTPUT: 1
        NOSE_HTML_OUT_FILE: nose_results.html
        NOSE_WITH_XUNIT: 1
    irrelevant-files: &documentation-files
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

# The Ceph job tests cinderlib without unnecessary libraries
- job:
    name: cinderlib-ceph-functional
    parent: openstack-tox-functional-with-sudo
    required-projects:
      - openstack/os-brick
      - openstack/cinder
    pre-run: playbooks/setup-ceph.yaml
    nodeset: centos-7
    vars:
      tox_environment:
        CL_FTEST_CFG: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/cinderlib'].src_dir }}/cinderlib/tests/functional/ceph.yaml"
        CL_FTEST_ROOT_HELPER: sudo
        # These come from great-great-grandparent tox job
        NOSE_WITH_HTML_OUTPUT: 1
        NOSE_HTML_OUT_FILE: nose_results.html
        NOSE_WITH_XUNIT: 1
    irrelevant-files: *documentation-files
